ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HC_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_63 = ', GC_63
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_65 = ', GC_65
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_102 = ', GC_102
