C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -4*Epsilon(1,2,3,-1)*P(-1,1) - 4*Epsilon(1,2,3,-1)*P(-1,2) -
C      4*Epsilon(1,2,3,-1)*P(-1,3)
C     
      SUBROUTINE VVVS1P0_1(V2, V3, S4, COUP, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      REAL*8 P1(0:3)
      REAL*8 M1
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      REAL*8 W1
      COMPLEX*16 DENOM
      COMPLEX*16 COUP
      COMPLEX*16 V1(6)
      COMPLEX*16 S4(*)
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      V1(1) = +V2(1)+V3(1)+S4(1)
      V1(2) = +V2(2)+V3(2)+S4(2)
      P1(0) = -DBLE(V1(1))
      P1(1) = -DBLE(V1(2))
      P1(2) = -DIMAG(V1(2))
      P1(3) = -DIMAG(V1(1))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1(3)= DENOM*(-4D0 )* CI * S4(3)*(V2(4)*(V3(5)*(-1D0)*(P1(3)
     $ +P2(3)+P3(3))+V3(6)*(P1(2)+P2(2)+P3(2)))+(V2(5)*(V3(4)*(P1(3)
     $ +P2(3)+P3(3))-V3(6)*(P1(1)+P2(1)+P3(1)))+V2(6)*(V3(4)*(-1D0)
     $ *(P1(2)+P2(2)+P3(2))+V3(5)*(P1(1)+P2(1)+P3(1)))))
      V1(4)= DENOM*4D0 * CI * S4(3)*(V2(3)*(V3(5)*(P1(3)+P2(3)+P3(3))
     $ -V3(6)*(P1(2)+P2(2)+P3(2)))+(V2(5)*(V3(3)*(-1D0)*(P1(3)+P2(3)
     $ +P3(3))+V3(6)*(P1(0)+P2(0)+P3(0)))+V2(6)*(V3(3)*(P1(2)+P2(2)
     $ +P3(2))-V3(5)*(P1(0)+P2(0)+P3(0)))))
      V1(5)= DENOM*4D0 * CI * S4(3)*(V2(3)*(V3(4)*(-1D0)*(P1(3)+P2(3)
     $ +P3(3))+V3(6)*(P1(1)+P2(1)+P3(1)))+(V2(4)*(V3(3)*(P1(3)+P2(3)
     $ +P3(3))-V3(6)*(P1(0)+P2(0)+P3(0)))+V2(6)*(V3(3)*(-1D0)*(P1(1)
     $ +P2(1)+P3(1))+V3(4)*(P1(0)+P2(0)+P3(0)))))
      V1(6)= DENOM*4D0 * CI * S4(3)*(V2(3)*(V3(4)*(P1(2)+P2(2)+P3(2))
     $ -V3(5)*(P1(1)+P2(1)+P3(1)))+(V2(4)*(V3(3)*(-1D0)*(P1(2)+P2(2)
     $ +P3(2))+V3(5)*(P1(0)+P2(0)+P3(0)))+V2(5)*(V3(3)*(P1(1)+P2(1)
     $ +P3(1))-V3(4)*(P1(0)+P2(0)+P3(0)))))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     -4*Epsilon(1,2,3,-1)*P(-1,1) - 4*Epsilon(1,2,3,-1)*P(-1,2) -
C      4*Epsilon(1,2,3,-1)*P(-1,3)
C     
      SUBROUTINE VVVS1_2P0_1(V2, V3, S4, COUP1, COUP2, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 COUP2
      COMPLEX*16 V3(*)
      REAL*8 P1(0:3)
      REAL*8 M1
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      REAL*8 W1
      COMPLEX*16 COUP1
      COMPLEX*16 DENOM
      INTEGER*4 I
      COMPLEX*16 VTMP(6)
      COMPLEX*16 V1(6)
      COMPLEX*16 S4(*)
      CALL VVVS1P0_1(V2,V3,S4,COUP1,M1,W1,V1)
      CALL VVVS2P0_1(V2,V3,S4,COUP2,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      END


