ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HC_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_73 = ', GC_73
      WRITE(*,2) 'GC_74 = ', GC_74
      WRITE(*,2) 'GC_75 = ', GC_75
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_98 = ', GC_98
      WRITE(*,2) 'GC_99 = ', GC_99
      WRITE(*,2) 'GC_100 = ', GC_100
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_102 = ', GC_102
      WRITE(*,2) 'GC_107 = ', GC_107
      WRITE(*,2) 'GC_108 = ', GC_108
      WRITE(*,2) 'GC_109 = ', GC_109
      WRITE(*,2) 'GC_110 = ', GC_110
