      SUBROUTINE SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.5.5, 2017-05-26
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g b~ > x0 b b~ b~ QCD<=1 QED<=99 QNP=0 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T
      REAL*8 MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,6) /-1,-1, 0,-1, 1, 1/
      DATA (NHEL(I,   2),I=1,6) /-1,-1, 0,-1, 1,-1/
      DATA (NHEL(I,   3),I=1,6) /-1,-1, 0,-1,-1, 1/
      DATA (NHEL(I,   4),I=1,6) /-1,-1, 0,-1,-1,-1/
      DATA (NHEL(I,   5),I=1,6) /-1,-1, 0, 1, 1, 1/
      DATA (NHEL(I,   6),I=1,6) /-1,-1, 0, 1, 1,-1/
      DATA (NHEL(I,   7),I=1,6) /-1,-1, 0, 1,-1, 1/
      DATA (NHEL(I,   8),I=1,6) /-1,-1, 0, 1,-1,-1/
      DATA (NHEL(I,   9),I=1,6) /-1, 1, 0,-1, 1, 1/
      DATA (NHEL(I,  10),I=1,6) /-1, 1, 0,-1, 1,-1/
      DATA (NHEL(I,  11),I=1,6) /-1, 1, 0,-1,-1, 1/
      DATA (NHEL(I,  12),I=1,6) /-1, 1, 0,-1,-1,-1/
      DATA (NHEL(I,  13),I=1,6) /-1, 1, 0, 1, 1, 1/
      DATA (NHEL(I,  14),I=1,6) /-1, 1, 0, 1, 1,-1/
      DATA (NHEL(I,  15),I=1,6) /-1, 1, 0, 1,-1, 1/
      DATA (NHEL(I,  16),I=1,6) /-1, 1, 0, 1,-1,-1/
      DATA (NHEL(I,  17),I=1,6) / 1,-1, 0,-1, 1, 1/
      DATA (NHEL(I,  18),I=1,6) / 1,-1, 0,-1, 1,-1/
      DATA (NHEL(I,  19),I=1,6) / 1,-1, 0,-1,-1, 1/
      DATA (NHEL(I,  20),I=1,6) / 1,-1, 0,-1,-1,-1/
      DATA (NHEL(I,  21),I=1,6) / 1,-1, 0, 1, 1, 1/
      DATA (NHEL(I,  22),I=1,6) / 1,-1, 0, 1, 1,-1/
      DATA (NHEL(I,  23),I=1,6) / 1,-1, 0, 1,-1, 1/
      DATA (NHEL(I,  24),I=1,6) / 1,-1, 0, 1,-1,-1/
      DATA (NHEL(I,  25),I=1,6) / 1, 1, 0,-1, 1, 1/
      DATA (NHEL(I,  26),I=1,6) / 1, 1, 0,-1, 1,-1/
      DATA (NHEL(I,  27),I=1,6) / 1, 1, 0,-1,-1, 1/
      DATA (NHEL(I,  28),I=1,6) / 1, 1, 0,-1,-1,-1/
      DATA (NHEL(I,  29),I=1,6) / 1, 1, 0, 1, 1, 1/
      DATA (NHEL(I,  30),I=1,6) / 1, 1, 0, 1, 1,-1/
      DATA (NHEL(I,  31),I=1,6) / 1, 1, 0, 1,-1, 1/
      DATA (NHEL(I,  32),I=1,6) / 1, 1, 0, 1,-1,-1/
      DATA IDEN/192/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.IS_BORN_HEL_SELECTED(IHEL))
     $        THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.5.5, 2017-05-26
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g b~ > x0 b b~ b~ QCD<=1 QED<=99 QNP=0 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=136)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=30, NCOLOR=4)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  4) /   12,    4,    4,    0/
C     1 T(1,2,5) T(4,6)
      DATA DENOM(2)/1/
      DATA (CF(I,  2),I=  1,  4) /    4,   12,    0,    4/
C     1 T(1,2,6) T(4,5)
      DATA DENOM(3)/1/
      DATA (CF(I,  3),I=  1,  4) /    4,    0,   12,    4/
C     1 T(1,4,5) T(2,6)
      DATA DENOM(4)/1/
      DATA (CF(I,  4),I=  1,  4) /    0,    4,    4,   12/
C     1 T(1,4,6) T(2,5)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),MDL_MB,NHEL(2),-1*IC(2),W(1,2))
      CALL SXXXXX(P(0,3),+1*IC(3),W(1,3))
      CALL OXXXXX(P(0,4),MDL_MB,NHEL(4),+1*IC(4),W(1,4))
      CALL IXXXXX(P(0,5),MDL_MB,NHEL(5),-1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),MDL_MB,NHEL(6),-1*IC(6),W(1,6))
      CALL FFV1_2(W(1,5),W(1,1),GC_7,MDL_MB,ZERO,W(1,7))
      CALL FFS1_2_1(W(1,2),W(1,3),GC_102,GC_101,MDL_MB,ZERO,W(1,8))
      CALL FFS1_2_3(W(1,7),W(1,4),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFS1_2_0(W(1,6),W(1,8),W(1,9),GC_102,GC_101,AMP(1))
      CALL FFV1P0_3(W(1,7),W(1,4),GC_1,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,6),W(1,8),W(1,10),GC_1,AMP(2))
      CALL FFV3_4_3(W(1,7),W(1,4),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,11))
C     Amplitude(s) for diagram number 3
      CALL FFV3_4_0(W(1,6),W(1,8),W(1,11),GC_77,GC_89,AMP(3))
      CALL FFS1_2_3(W(1,6),W(1,4),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1,12)
     $ )
C     Amplitude(s) for diagram number 4
      CALL FFS1_2_0(W(1,7),W(1,8),W(1,12),GC_102,GC_101,AMP(4))
      CALL FFV1P0_3(W(1,6),W(1,4),GC_1,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 5
      CALL FFV1_0(W(1,7),W(1,8),W(1,13),GC_1,AMP(5))
      CALL FFV3_4_3(W(1,6),W(1,4),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,14))
C     Amplitude(s) for diagram number 6
      CALL FFV3_4_0(W(1,7),W(1,8),W(1,14),GC_77,GC_89,AMP(6))
      CALL FFS1_2_1(W(1,4),W(1,3),GC_102,GC_101,MDL_MB,ZERO,W(1,15))
      CALL FFS1_2_3(W(1,7),W(1,2),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1,16)
     $ )
C     Amplitude(s) for diagram number 7
      CALL FFS1_2_0(W(1,6),W(1,15),W(1,16),GC_102,GC_101,AMP(7))
      CALL FFV1P0_3(W(1,7),W(1,2),GC_1,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 8
      CALL FFV1_0(W(1,6),W(1,15),W(1,17),GC_1,AMP(8))
      CALL FFV3_4_3(W(1,7),W(1,2),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,18))
C     Amplitude(s) for diagram number 9
      CALL FFV3_4_0(W(1,6),W(1,15),W(1,18),GC_77,GC_89,AMP(9))
      CALL FFS1_2_3(W(1,6),W(1,2),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1,19)
     $ )
C     Amplitude(s) for diagram number 10
      CALL FFS1_2_0(W(1,7),W(1,15),W(1,19),GC_102,GC_101,AMP(10))
      CALL FFV1P0_3(W(1,6),W(1,2),GC_1,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 11
      CALL FFV1_0(W(1,7),W(1,15),W(1,20),GC_1,AMP(11))
      CALL FFV3_4_3(W(1,6),W(1,2),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,21))
C     Amplitude(s) for diagram number 12
      CALL FFV3_4_0(W(1,7),W(1,15),W(1,21),GC_77,GC_89,AMP(12))
      CALL FFS1_2_2(W(1,6),W(1,3),GC_102,GC_101,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 13
      CALL FFS1_2_0(W(1,22),W(1,4),W(1,16),GC_102,GC_101,AMP(13))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,22),W(1,4),W(1,17),GC_1,AMP(14))
C     Amplitude(s) for diagram number 15
      CALL FFV3_4_0(W(1,22),W(1,4),W(1,18),GC_77,GC_89,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL FFS1_2_0(W(1,22),W(1,2),W(1,9),GC_102,GC_101,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV1_0(W(1,22),W(1,2),W(1,10),GC_1,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFV3_4_0(W(1,22),W(1,2),W(1,11),GC_77,GC_89,AMP(18))
      CALL FFS1_2_2(W(1,7),W(1,3),GC_102,GC_101,MDL_MB,ZERO,W(1,10))
C     Amplitude(s) for diagram number 19
      CALL FFS1_2_0(W(1,10),W(1,4),W(1,19),GC_102,GC_101,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL SSS1_0(W(1,3),W(1,19),W(1,9),GC_98,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL FFV1_0(W(1,10),W(1,4),W(1,20),GC_1,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV3_4_0(W(1,10),W(1,4),W(1,21),GC_77,GC_89,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL VVS4_0(W(1,21),W(1,11),W(1,3),GC_100,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFS1_2_0(W(1,10),W(1,2),W(1,12),GC_102,GC_101,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL SSS1_0(W(1,3),W(1,12),W(1,16),GC_98,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFV1_0(W(1,10),W(1,2),W(1,13),GC_1,AMP(26))
C     Amplitude(s) for diagram number 27
      CALL FFV3_4_0(W(1,10),W(1,2),W(1,14),GC_77,GC_89,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL VVS4_0(W(1,14),W(1,18),W(1,3),GC_100,AMP(28))
      CALL FFV1_1(W(1,2),W(1,1),GC_7,MDL_MB,ZERO,W(1,18))
      CALL FFS1_2_2(W(1,5),W(1,3),GC_102,GC_101,MDL_MB,ZERO,W(1,10))
      CALL FFS1_2_3(W(1,6),W(1,18),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1
     $ ,16))
C     Amplitude(s) for diagram number 29
      CALL FFS1_2_0(W(1,10),W(1,4),W(1,16),GC_102,GC_101,AMP(29))
      CALL FFV1P0_3(W(1,6),W(1,18),GC_1,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 30
      CALL FFV1_0(W(1,10),W(1,4),W(1,11),GC_1,AMP(30))
      CALL FFV3_4_3(W(1,6),W(1,18),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,9))
C     Amplitude(s) for diagram number 31
      CALL FFV3_4_0(W(1,10),W(1,4),W(1,9),GC_77,GC_89,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL FFS1_2_0(W(1,10),W(1,18),W(1,12),GC_102,GC_101,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFV1_0(W(1,10),W(1,18),W(1,13),GC_1,AMP(33))
C     Amplitude(s) for diagram number 34
      CALL FFV3_4_0(W(1,10),W(1,18),W(1,14),GC_77,GC_89,AMP(34))
      CALL FFS1_2_3(W(1,5),W(1,4),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1,7))
      CALL FFS1_2_1(W(1,18),W(1,3),GC_102,GC_101,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 35
      CALL FFS1_2_0(W(1,6),W(1,17),W(1,7),GC_102,GC_101,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL SSS1_0(W(1,7),W(1,3),W(1,16),GC_98,AMP(36))
      CALL FFV1P0_3(W(1,5),W(1,4),GC_1,ZERO,ZERO,W(1,23))
C     Amplitude(s) for diagram number 37
      CALL FFV1_0(W(1,6),W(1,17),W(1,23),GC_1,AMP(37))
      CALL FFV3_4_3(W(1,5),W(1,4),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,24))
C     Amplitude(s) for diagram number 38
      CALL FFV3_4_0(W(1,6),W(1,17),W(1,24),GC_77,GC_89,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL VVS4_0(W(1,24),W(1,9),W(1,3),GC_100,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFS1_2_0(W(1,22),W(1,18),W(1,7),GC_102,GC_101,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL FFV1_0(W(1,22),W(1,18),W(1,23),GC_1,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV3_4_0(W(1,22),W(1,18),W(1,24),GC_77,GC_89,AMP(42))
      CALL FFS1_2_3(W(1,5),W(1,18),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1
     $ ,25))
C     Amplitude(s) for diagram number 43
      CALL FFS1_2_0(W(1,6),W(1,15),W(1,25),GC_102,GC_101,AMP(43))
      CALL FFV1P0_3(W(1,5),W(1,18),GC_1,ZERO,ZERO,W(1,26))
C     Amplitude(s) for diagram number 44
      CALL FFV1_0(W(1,6),W(1,15),W(1,26),GC_1,AMP(44))
      CALL FFV3_4_3(W(1,5),W(1,18),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,27))
C     Amplitude(s) for diagram number 45
      CALL FFV3_4_0(W(1,6),W(1,15),W(1,27),GC_77,GC_89,AMP(45))
C     Amplitude(s) for diagram number 46
      CALL FFS1_2_0(W(1,5),W(1,15),W(1,16),GC_102,GC_101,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL FFV1_0(W(1,5),W(1,15),W(1,11),GC_1,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL FFV3_4_0(W(1,5),W(1,15),W(1,9),GC_77,GC_89,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL FFS1_2_0(W(1,22),W(1,4),W(1,25),GC_102,GC_101,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL FFV1_0(W(1,22),W(1,4),W(1,26),GC_1,AMP(50))
C     Amplitude(s) for diagram number 51
      CALL FFV3_4_0(W(1,22),W(1,4),W(1,27),GC_77,GC_89,AMP(51))
C     Amplitude(s) for diagram number 52
      CALL SSS1_0(W(1,3),W(1,12),W(1,25),GC_98,AMP(52))
C     Amplitude(s) for diagram number 53
      CALL FFS1_2_0(W(1,5),W(1,17),W(1,12),GC_102,GC_101,AMP(53))
C     Amplitude(s) for diagram number 54
      CALL FFV1_0(W(1,5),W(1,17),W(1,13),GC_1,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL VVS4_0(W(1,14),W(1,27),W(1,3),GC_100,AMP(55))
C     Amplitude(s) for diagram number 56
      CALL FFV3_4_0(W(1,5),W(1,17),W(1,14),GC_77,GC_89,AMP(56))
      CALL FFV1_1(W(1,4),W(1,1),GC_7,MDL_MB,ZERO,W(1,17))
      CALL FFS1_2_3(W(1,6),W(1,17),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1
     $ ,27))
C     Amplitude(s) for diagram number 57
      CALL FFS1_2_0(W(1,10),W(1,2),W(1,27),GC_102,GC_101,AMP(57))
      CALL FFV1P0_3(W(1,6),W(1,17),GC_1,ZERO,ZERO,W(1,25))
C     Amplitude(s) for diagram number 58
      CALL FFV1_0(W(1,10),W(1,2),W(1,25),GC_1,AMP(58))
      CALL FFV3_4_3(W(1,6),W(1,17),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,26))
C     Amplitude(s) for diagram number 59
      CALL FFV3_4_0(W(1,10),W(1,2),W(1,26),GC_77,GC_89,AMP(59))
C     Amplitude(s) for diagram number 60
      CALL FFS1_2_0(W(1,10),W(1,17),W(1,19),GC_102,GC_101,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL FFV1_0(W(1,10),W(1,17),W(1,20),GC_1,AMP(61))
C     Amplitude(s) for diagram number 62
      CALL FFV3_4_0(W(1,10),W(1,17),W(1,21),GC_77,GC_89,AMP(62))
      CALL FFS1_2_3(W(1,5),W(1,2),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1,9))
      CALL FFS1_2_1(W(1,17),W(1,3),GC_102,GC_101,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 63
      CALL FFS1_2_0(W(1,6),W(1,11),W(1,9),GC_102,GC_101,AMP(63))
C     Amplitude(s) for diagram number 64
      CALL SSS1_0(W(1,9),W(1,3),W(1,27),GC_98,AMP(64))
      CALL FFV1P0_3(W(1,5),W(1,2),GC_1,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 65
      CALL FFV1_0(W(1,6),W(1,11),W(1,16),GC_1,AMP(65))
      CALL FFV3_4_3(W(1,5),W(1,2),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,18))
C     Amplitude(s) for diagram number 66
      CALL FFV3_4_0(W(1,6),W(1,11),W(1,18),GC_77,GC_89,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL VVS4_0(W(1,18),W(1,26),W(1,3),GC_100,AMP(67))
C     Amplitude(s) for diagram number 68
      CALL FFS1_2_0(W(1,22),W(1,17),W(1,9),GC_102,GC_101,AMP(68))
C     Amplitude(s) for diagram number 69
      CALL FFV1_0(W(1,22),W(1,17),W(1,16),GC_1,AMP(69))
C     Amplitude(s) for diagram number 70
      CALL FFV3_4_0(W(1,22),W(1,17),W(1,18),GC_77,GC_89,AMP(70))
      CALL FFS1_2_3(W(1,5),W(1,17),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1
     $ ,28))
C     Amplitude(s) for diagram number 71
      CALL FFS1_2_0(W(1,6),W(1,8),W(1,28),GC_102,GC_101,AMP(71))
      CALL FFV1P0_3(W(1,5),W(1,17),GC_1,ZERO,ZERO,W(1,29))
C     Amplitude(s) for diagram number 72
      CALL FFV1_0(W(1,6),W(1,8),W(1,29),GC_1,AMP(72))
      CALL FFV3_4_3(W(1,5),W(1,17),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,30))
C     Amplitude(s) for diagram number 73
      CALL FFV3_4_0(W(1,6),W(1,8),W(1,30),GC_77,GC_89,AMP(73))
C     Amplitude(s) for diagram number 74
      CALL FFS1_2_0(W(1,5),W(1,8),W(1,27),GC_102,GC_101,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL FFV1_0(W(1,5),W(1,8),W(1,25),GC_1,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL FFV3_4_0(W(1,5),W(1,8),W(1,26),GC_77,GC_89,AMP(76))
C     Amplitude(s) for diagram number 77
      CALL FFS1_2_0(W(1,22),W(1,2),W(1,28),GC_102,GC_101,AMP(77))
C     Amplitude(s) for diagram number 78
      CALL FFV1_0(W(1,22),W(1,2),W(1,29),GC_1,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFV3_4_0(W(1,22),W(1,2),W(1,30),GC_77,GC_89,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL SSS1_0(W(1,3),W(1,19),W(1,28),GC_98,AMP(80))
C     Amplitude(s) for diagram number 81
      CALL FFS1_2_0(W(1,5),W(1,11),W(1,19),GC_102,GC_101,AMP(81))
C     Amplitude(s) for diagram number 82
      CALL FFV1_0(W(1,5),W(1,11),W(1,20),GC_1,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL VVS4_0(W(1,21),W(1,30),W(1,3),GC_100,AMP(83))
C     Amplitude(s) for diagram number 84
      CALL FFV3_4_0(W(1,5),W(1,11),W(1,21),GC_77,GC_89,AMP(84))
      CALL FFV1_2(W(1,6),W(1,1),GC_7,MDL_MB,ZERO,W(1,11))
      CALL FFS1_2_3(W(1,11),W(1,2),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1
     $ ,30))
C     Amplitude(s) for diagram number 85
      CALL FFS1_2_0(W(1,10),W(1,4),W(1,30),GC_102,GC_101,AMP(85))
      CALL FFV1P0_3(W(1,11),W(1,2),GC_1,ZERO,ZERO,W(1,28))
C     Amplitude(s) for diagram number 86
      CALL FFV1_0(W(1,10),W(1,4),W(1,28),GC_1,AMP(86))
      CALL FFV3_4_3(W(1,11),W(1,2),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,29))
C     Amplitude(s) for diagram number 87
      CALL FFV3_4_0(W(1,10),W(1,4),W(1,29),GC_77,GC_89,AMP(87))
      CALL FFS1_2_3(W(1,11),W(1,4),GC_102,GC_101,MDL_MX0,MDL_WX0,W(1
     $ ,26))
C     Amplitude(s) for diagram number 88
      CALL FFS1_2_0(W(1,10),W(1,2),W(1,26),GC_102,GC_101,AMP(88))
      CALL FFV1P0_3(W(1,11),W(1,4),GC_1,ZERO,ZERO,W(1,25))
C     Amplitude(s) for diagram number 89
      CALL FFV1_0(W(1,10),W(1,2),W(1,25),GC_1,AMP(89))
      CALL FFV3_4_3(W(1,11),W(1,4),GC_77,GC_89,MDL_MZ,MDL_WZ,W(1,27))
C     Amplitude(s) for diagram number 90
      CALL FFV3_4_0(W(1,10),W(1,2),W(1,27),GC_77,GC_89,AMP(90))
      CALL FFS1_2_2(W(1,11),W(1,3),GC_102,GC_101,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 91
      CALL FFS1_2_0(W(1,17),W(1,4),W(1,9),GC_102,GC_101,AMP(91))
C     Amplitude(s) for diagram number 92
      CALL SSS1_0(W(1,9),W(1,3),W(1,26),GC_98,AMP(92))
C     Amplitude(s) for diagram number 93
      CALL FFV1_0(W(1,17),W(1,4),W(1,16),GC_1,AMP(93))
C     Amplitude(s) for diagram number 94
      CALL FFV3_4_0(W(1,17),W(1,4),W(1,18),GC_77,GC_89,AMP(94))
C     Amplitude(s) for diagram number 95
      CALL VVS4_0(W(1,18),W(1,27),W(1,3),GC_100,AMP(95))
C     Amplitude(s) for diagram number 96
      CALL FFS1_2_0(W(1,11),W(1,15),W(1,9),GC_102,GC_101,AMP(96))
C     Amplitude(s) for diagram number 97
      CALL FFV1_0(W(1,11),W(1,15),W(1,16),GC_1,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL FFV3_4_0(W(1,11),W(1,15),W(1,18),GC_77,GC_89,AMP(98))
C     Amplitude(s) for diagram number 99
      CALL FFS1_2_0(W(1,17),W(1,2),W(1,7),GC_102,GC_101,AMP(99))
C     Amplitude(s) for diagram number 100
      CALL SSS1_0(W(1,7),W(1,3),W(1,30),GC_98,AMP(100))
C     Amplitude(s) for diagram number 101
      CALL FFV1_0(W(1,17),W(1,2),W(1,23),GC_1,AMP(101))
C     Amplitude(s) for diagram number 102
      CALL FFV3_4_0(W(1,17),W(1,2),W(1,24),GC_77,GC_89,AMP(102))
C     Amplitude(s) for diagram number 103
      CALL VVS4_0(W(1,24),W(1,29),W(1,3),GC_100,AMP(103))
C     Amplitude(s) for diagram number 104
      CALL FFS1_2_0(W(1,11),W(1,8),W(1,7),GC_102,GC_101,AMP(104))
C     Amplitude(s) for diagram number 105
      CALL FFV1_0(W(1,11),W(1,8),W(1,23),GC_1,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL FFV3_4_0(W(1,11),W(1,8),W(1,24),GC_77,GC_89,AMP(106))
C     Amplitude(s) for diagram number 107
      CALL FFS1_2_0(W(1,5),W(1,8),W(1,26),GC_102,GC_101,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV1_0(W(1,5),W(1,8),W(1,25),GC_1,AMP(108))
C     Amplitude(s) for diagram number 109
      CALL FFV3_4_0(W(1,5),W(1,8),W(1,27),GC_77,GC_89,AMP(109))
C     Amplitude(s) for diagram number 110
      CALL FFS1_2_0(W(1,5),W(1,15),W(1,30),GC_102,GC_101,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV1_0(W(1,5),W(1,15),W(1,28),GC_1,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV3_4_0(W(1,5),W(1,15),W(1,29),GC_77,GC_89,AMP(112))
      CALL FFV1_2(W(1,10),W(1,1),GC_7,MDL_MB,ZERO,W(1,29))
C     Amplitude(s) for diagram number 113
      CALL FFS1_2_0(W(1,29),W(1,4),W(1,19),GC_102,GC_101,AMP(113))
C     Amplitude(s) for diagram number 114
      CALL FFV1_0(W(1,29),W(1,4),W(1,20),GC_1,AMP(114))
C     Amplitude(s) for diagram number 115
      CALL FFV3_4_0(W(1,29),W(1,4),W(1,21),GC_77,GC_89,AMP(115))
C     Amplitude(s) for diagram number 116
      CALL FFS1_2_0(W(1,29),W(1,2),W(1,12),GC_102,GC_101,AMP(116))
C     Amplitude(s) for diagram number 117
      CALL FFV1_0(W(1,29),W(1,2),W(1,13),GC_1,AMP(117))
C     Amplitude(s) for diagram number 118
      CALL FFV3_4_0(W(1,29),W(1,2),W(1,14),GC_77,GC_89,AMP(118))
      CALL FFV1_1(W(1,15),W(1,1),GC_7,MDL_MB,ZERO,W(1,29))
C     Amplitude(s) for diagram number 119
      CALL FFS1_2_0(W(1,6),W(1,29),W(1,9),GC_102,GC_101,AMP(119))
C     Amplitude(s) for diagram number 120
      CALL FFV1_0(W(1,6),W(1,29),W(1,16),GC_1,AMP(120))
C     Amplitude(s) for diagram number 121
      CALL FFV3_4_0(W(1,6),W(1,29),W(1,18),GC_77,GC_89,AMP(121))
      CALL FFV1_2(W(1,22),W(1,1),GC_7,MDL_MB,ZERO,W(1,15))
C     Amplitude(s) for diagram number 122
      CALL FFS1_2_0(W(1,15),W(1,4),W(1,9),GC_102,GC_101,AMP(122))
C     Amplitude(s) for diagram number 123
      CALL FFV1_0(W(1,15),W(1,4),W(1,16),GC_1,AMP(123))
C     Amplitude(s) for diagram number 124
      CALL FFV3_4_0(W(1,15),W(1,4),W(1,18),GC_77,GC_89,AMP(124))
      CALL FFV1_1(W(1,8),W(1,1),GC_7,MDL_MB,ZERO,W(1,18))
C     Amplitude(s) for diagram number 125
      CALL FFS1_2_0(W(1,6),W(1,18),W(1,7),GC_102,GC_101,AMP(125))
C     Amplitude(s) for diagram number 126
      CALL FFV1_0(W(1,6),W(1,18),W(1,23),GC_1,AMP(126))
C     Amplitude(s) for diagram number 127
      CALL FFV3_4_0(W(1,6),W(1,18),W(1,24),GC_77,GC_89,AMP(127))
C     Amplitude(s) for diagram number 128
      CALL FFS1_2_0(W(1,15),W(1,2),W(1,7),GC_102,GC_101,AMP(128))
C     Amplitude(s) for diagram number 129
      CALL FFV1_0(W(1,15),W(1,2),W(1,23),GC_1,AMP(129))
C     Amplitude(s) for diagram number 130
      CALL FFV3_4_0(W(1,15),W(1,2),W(1,24),GC_77,GC_89,AMP(130))
C     Amplitude(s) for diagram number 131
      CALL FFS1_2_0(W(1,5),W(1,18),W(1,12),GC_102,GC_101,AMP(131))
C     Amplitude(s) for diagram number 132
      CALL FFV1_0(W(1,5),W(1,18),W(1,13),GC_1,AMP(132))
C     Amplitude(s) for diagram number 133
      CALL FFV3_4_0(W(1,5),W(1,18),W(1,14),GC_77,GC_89,AMP(133))
C     Amplitude(s) for diagram number 134
      CALL FFS1_2_0(W(1,5),W(1,29),W(1,19),GC_102,GC_101,AMP(134))
C     Amplitude(s) for diagram number 135
      CALL FFV1_0(W(1,5),W(1,29),W(1,20),GC_1,AMP(135))
C     Amplitude(s) for diagram number 136
      CALL FFV3_4_0(W(1,5),W(1,29),W(1,21),GC_77,GC_89,AMP(136))
      JAMP(1)=-AMP(4)-AMP(5)-AMP(6)-AMP(7)-AMP(8)-AMP(9)-AMP(13)
     $ -AMP(14)-AMP(15)-AMP(24)-AMP(25)-AMP(26)-AMP(27)-AMP(28)-AMP(32)
     $ -AMP(33)-AMP(34)-AMP(43)-AMP(44)-AMP(45)-AMP(49)-AMP(50)-AMP(51)
     $ -AMP(52)-AMP(53)-AMP(54)-AMP(55)-AMP(56)-AMP(116)-AMP(117)
     $ -AMP(118)-AMP(131)-AMP(132)-AMP(133)
      JAMP(2)=+AMP(29)+AMP(30)+AMP(31)+AMP(35)+AMP(36)+AMP(37)+AMP(38)
     $ +AMP(39)+AMP(40)+AMP(41)+AMP(42)+AMP(46)+AMP(47)+AMP(48)+AMP(85)
     $ +AMP(86)+AMP(87)+AMP(99)+AMP(100)+AMP(101)+AMP(102)+AMP(103)
     $ +AMP(104)+AMP(105)+AMP(106)+AMP(110)+AMP(111)+AMP(112)+AMP(125)
     $ +AMP(126)+AMP(127)+AMP(128)+AMP(129)+AMP(130)
      JAMP(3)=+AMP(1)+AMP(2)+AMP(3)+AMP(10)+AMP(11)+AMP(12)+AMP(16)
     $ +AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)+AMP(22)+AMP(23)+AMP(60)
     $ +AMP(61)+AMP(62)+AMP(71)+AMP(72)+AMP(73)+AMP(77)+AMP(78)+AMP(79)
     $ +AMP(80)+AMP(81)+AMP(82)+AMP(83)+AMP(84)+AMP(113)+AMP(114)
     $ +AMP(115)+AMP(134)+AMP(135)+AMP(136)
      JAMP(4)=-AMP(57)-AMP(58)-AMP(59)-AMP(63)-AMP(64)-AMP(65)-AMP(66)
     $ -AMP(67)-AMP(68)-AMP(69)-AMP(70)-AMP(74)-AMP(75)-AMP(76)-AMP(88)
     $ -AMP(89)-AMP(90)-AMP(91)-AMP(92)-AMP(93)-AMP(94)-AMP(95)-AMP(96)
     $ -AMP(97)-AMP(98)-AMP(107)-AMP(108)-AMP(109)-AMP(119)-AMP(120)
     $ -AMP(121)-AMP(122)-AMP(123)-AMP(124)

      MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        MATRIX = MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE GET_ME(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE INITIALISE(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*180 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NCOMB
      PARAMETER (NCOMB=32)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/BORN_HEL_CONFIGS/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

