      SUBROUTINE SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.5.2, 2016-12-10
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g g > x0 g u u~ QNP<=2 WEIGHTED<=5 @1
C     Process: g g > x0 g c c~ QNP<=2 WEIGHTED<=5 @1
C     Process: g g > x0 g d d~ QNP<=2 WEIGHTED<=5 @1
C     Process: g g > x0 g s s~ QNP<=2 WEIGHTED<=5 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T
      REAL*8 MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,6) /-1,-1, 0,-1,-1, 1/
      DATA (NHEL(I,   2),I=1,6) /-1,-1, 0,-1,-1,-1/
      DATA (NHEL(I,   3),I=1,6) /-1,-1, 0,-1, 1, 1/
      DATA (NHEL(I,   4),I=1,6) /-1,-1, 0,-1, 1,-1/
      DATA (NHEL(I,   5),I=1,6) /-1,-1, 0, 1,-1, 1/
      DATA (NHEL(I,   6),I=1,6) /-1,-1, 0, 1,-1,-1/
      DATA (NHEL(I,   7),I=1,6) /-1,-1, 0, 1, 1, 1/
      DATA (NHEL(I,   8),I=1,6) /-1,-1, 0, 1, 1,-1/
      DATA (NHEL(I,   9),I=1,6) /-1, 1, 0,-1,-1, 1/
      DATA (NHEL(I,  10),I=1,6) /-1, 1, 0,-1,-1,-1/
      DATA (NHEL(I,  11),I=1,6) /-1, 1, 0,-1, 1, 1/
      DATA (NHEL(I,  12),I=1,6) /-1, 1, 0,-1, 1,-1/
      DATA (NHEL(I,  13),I=1,6) /-1, 1, 0, 1,-1, 1/
      DATA (NHEL(I,  14),I=1,6) /-1, 1, 0, 1,-1,-1/
      DATA (NHEL(I,  15),I=1,6) /-1, 1, 0, 1, 1, 1/
      DATA (NHEL(I,  16),I=1,6) /-1, 1, 0, 1, 1,-1/
      DATA (NHEL(I,  17),I=1,6) / 1,-1, 0,-1,-1, 1/
      DATA (NHEL(I,  18),I=1,6) / 1,-1, 0,-1,-1,-1/
      DATA (NHEL(I,  19),I=1,6) / 1,-1, 0,-1, 1, 1/
      DATA (NHEL(I,  20),I=1,6) / 1,-1, 0,-1, 1,-1/
      DATA (NHEL(I,  21),I=1,6) / 1,-1, 0, 1,-1, 1/
      DATA (NHEL(I,  22),I=1,6) / 1,-1, 0, 1,-1,-1/
      DATA (NHEL(I,  23),I=1,6) / 1,-1, 0, 1, 1, 1/
      DATA (NHEL(I,  24),I=1,6) / 1,-1, 0, 1, 1,-1/
      DATA (NHEL(I,  25),I=1,6) / 1, 1, 0,-1,-1, 1/
      DATA (NHEL(I,  26),I=1,6) / 1, 1, 0,-1,-1,-1/
      DATA (NHEL(I,  27),I=1,6) / 1, 1, 0,-1, 1, 1/
      DATA (NHEL(I,  28),I=1,6) / 1, 1, 0,-1, 1,-1/
      DATA (NHEL(I,  29),I=1,6) / 1, 1, 0, 1,-1, 1/
      DATA (NHEL(I,  30),I=1,6) / 1, 1, 0, 1,-1,-1/
      DATA (NHEL(I,  31),I=1,6) / 1, 1, 0, 1, 1, 1/
      DATA (NHEL(I,  32),I=1,6) / 1, 1, 0, 1, 1,-1/
      DATA IDEN/256/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     
C     FUNCTIONS
C     
      LOGICAL IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.IS_BORN_HEL_SELECTED(IHEL))
     $        THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.5.2, 2016-12-10
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g g > x0 g u u~ QNP<=2 WEIGHTED<=5 @1
C     Process: g g > x0 g c c~ QNP<=2 WEIGHTED<=5 @1
C     Process: g g > x0 g d d~ QNP<=2 WEIGHTED<=5 @1
C     Process: g g > x0 g s s~ QNP<=2 WEIGHTED<=5 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=90)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=18, NCOLOR=9)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/9/
      DATA (CF(I,  1),I=  1,  6) /   64,   -8,   24,   -8,    1,   -3/
      DATA (CF(I,  1),I=  7,  9) /    1,   10,   24/
C     1 T(1,2,4,5,6)
      DATA DENOM(2)/9/
      DATA (CF(I,  2),I=  1,  6) /   -8,   64,   24,    1,   10,   24/
      DATA (CF(I,  2),I=  7,  9) /   -8,    1,   -3/
C     1 T(1,4,2,5,6)
      DATA DENOM(3)/3/
      DATA (CF(I,  3),I=  1,  6) /    8,    8,   24,   -1,    8,    3/
      DATA (CF(I,  3),I=  7,  9) /   -1,    8,    3/
C     1 T(1,5,6) Tr(2,4)
      DATA DENOM(4)/9/
      DATA (CF(I,  4),I=  1,  6) /   -8,    1,   -3,   64,   -8,   24/
      DATA (CF(I,  4),I=  7,  9) /   10,    1,   24/
C     1 T(2,1,4,5,6)
      DATA DENOM(5)/9/
      DATA (CF(I,  5),I=  1,  6) /    1,   10,   24,   -8,   64,   24/
      DATA (CF(I,  5),I=  7,  9) /    1,   -8,   -3/
C     1 T(2,4,1,5,6)
      DATA DENOM(6)/3/
      DATA (CF(I,  6),I=  1,  6) /   -1,    8,    3,    8,    8,   24/
      DATA (CF(I,  6),I=  7,  9) /    8,   -1,    3/
C     1 T(2,5,6) Tr(1,4)
      DATA DENOM(7)/9/
      DATA (CF(I,  7),I=  1,  6) /    1,   -8,   -3,   10,    1,   24/
      DATA (CF(I,  7),I=  7,  9) /   64,   -8,   24/
C     1 T(4,1,2,5,6)
      DATA DENOM(8)/9/
      DATA (CF(I,  8),I=  1,  6) /   10,    1,   24,    1,   -8,   -3/
      DATA (CF(I,  8),I=  7,  9) /   -8,   64,   24/
C     1 T(4,2,1,5,6)
      DATA DENOM(9)/3/
      DATA (CF(I,  9),I=  1,  6) /    8,   -1,    3,    8,   -1,    3/
      DATA (CF(I,  9),I=  7,  9) /    8,    8,   24/
C     1 T(4,5,6) Tr(1,2)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL SXXXXX(P(0,3),+1*IC(3),W(1,3))
      CALL VXXXXX(P(0,4),ZERO,NHEL(4),+1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1*IC(6),W(1,6))
      CALL VVV8P0_1(W(1,1),W(1,2),GC_6,ZERO,ZERO,W(1,7))
      CALL VVS2_6P0_1(W(1,4),W(1,3),GC_64,GC_10,ZERO,ZERO,W(1,8))
      CALL FFV1_1(W(1,5),W(1,7),GC_7,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,6),W(1,9),W(1,8),GC_7,AMP(1))
      CALL FFV1_2(W(1,6),W(1,7),GC_7,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,9),W(1,5),W(1,8),GC_7,AMP(2))
      CALL FFV1P0_3(W(1,6),W(1,5),GC_7,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 3
      CALL VVV8_0(W(1,7),W(1,8),W(1,9),GC_6,AMP(3))
      CALL FFV1_1(W(1,5),W(1,4),GC_7,ZERO,ZERO,W(1,10))
      CALL VVS2_6P0_1(W(1,7),W(1,3),GC_64,GC_10,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 4
      CALL FFV1_0(W(1,6),W(1,10),W(1,11),GC_7,AMP(4))
      CALL FFV1_2(W(1,6),W(1,4),GC_7,ZERO,ZERO,W(1,12))
C     Amplitude(s) for diagram number 5
      CALL FFV1_0(W(1,12),W(1,5),W(1,11),GC_7,AMP(5))
      CALL VVS2_6_3(W(1,1),W(1,2),GC_64,GC_10,MDL_MX0,MDL_WX0,W(1,13))
C     Amplitude(s) for diagram number 6
      CALL VVSS1_3_0(W(1,4),W(1,9),W(1,13),W(1,3),GC_62,GC_13,AMP(6))
C     Amplitude(s) for diagram number 7
      CALL VVVS1_2_0(W(1,7),W(1,4),W(1,9),W(1,3),GC_65,GC_11,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL VVV8_0(W(1,4),W(1,9),W(1,11),GC_6,AMP(8))
      CALL VVV8P0_1(W(1,7),W(1,4),GC_6,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 9
      CALL VVS2_6_0(W(1,9),W(1,11),W(1,3),GC_64,GC_10,AMP(9))
      CALL VVS2_6P0_1(W(1,1),W(1,3),GC_64,GC_10,ZERO,ZERO,W(1,11))
      CALL VVV8P0_1(W(1,2),W(1,4),GC_6,ZERO,ZERO,W(1,7))
      CALL FFV1_1(W(1,5),W(1,11),GC_7,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 10
      CALL FFV1_0(W(1,6),W(1,13),W(1,7),GC_7,AMP(10))
      CALL FFV1_2(W(1,6),W(1,11),GC_7,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 11
      CALL FFV1_0(W(1,14),W(1,5),W(1,7),GC_7,AMP(11))
C     Amplitude(s) for diagram number 12
      CALL VVV8_0(W(1,11),W(1,7),W(1,9),GC_6,AMP(12))
      CALL FFV1_1(W(1,5),W(1,2),GC_7,ZERO,ZERO,W(1,15))
      CALL VVV8P0_1(W(1,11),W(1,4),GC_6,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 13
      CALL FFV1_0(W(1,6),W(1,15),W(1,16),GC_7,AMP(13))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,14),W(1,15),W(1,4),GC_7,AMP(14))
C     Amplitude(s) for diagram number 15
      CALL FFV1_0(W(1,12),W(1,15),W(1,11),GC_7,AMP(15))
      CALL FFV1_2(W(1,6),W(1,2),GC_7,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 16
      CALL FFV1_0(W(1,17),W(1,5),W(1,16),GC_7,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV1_0(W(1,17),W(1,13),W(1,4),GC_7,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFV1_0(W(1,17),W(1,10),W(1,11),GC_7,AMP(18))
      CALL VVV8P0_1(W(1,11),W(1,2),GC_6,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 19
      CALL FFV1_0(W(1,6),W(1,10),W(1,18),GC_7,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL FFV1_0(W(1,14),W(1,10),W(1,2),GC_7,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL FFV1_0(W(1,12),W(1,5),W(1,18),GC_7,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV1_0(W(1,12),W(1,13),W(1,2),GC_7,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL VVVV1_0(W(1,11),W(1,2),W(1,4),W(1,9),GC_8,AMP(23))
      CALL VVVV3_0(W(1,11),W(1,2),W(1,4),W(1,9),GC_8,AMP(24))
      CALL VVVV4_0(W(1,11),W(1,2),W(1,4),W(1,9),GC_8,AMP(25))
C     Amplitude(s) for diagram number 24
      CALL VVV8_0(W(1,4),W(1,9),W(1,18),GC_6,AMP(26))
C     Amplitude(s) for diagram number 25
      CALL VVV8_0(W(1,2),W(1,9),W(1,16),GC_6,AMP(27))
      CALL VVV8P0_1(W(1,1),W(1,4),GC_6,ZERO,ZERO,W(1,16))
      CALL VVS2_6P0_1(W(1,2),W(1,3),GC_64,GC_10,ZERO,ZERO,W(1,18))
      CALL FFV1_1(W(1,5),W(1,16),GC_7,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 26
      CALL FFV1_0(W(1,6),W(1,11),W(1,18),GC_7,AMP(28))
      CALL FFV1_2(W(1,6),W(1,16),GC_7,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 27
      CALL FFV1_0(W(1,11),W(1,5),W(1,18),GC_7,AMP(29))
C     Amplitude(s) for diagram number 28
      CALL VVV8_0(W(1,16),W(1,18),W(1,9),GC_6,AMP(30))
      CALL VVS2_6P0_1(W(1,16),W(1,3),GC_64,GC_10,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 29
      CALL FFV1_0(W(1,6),W(1,15),W(1,11),GC_7,AMP(31))
C     Amplitude(s) for diagram number 30
      CALL FFV1_0(W(1,17),W(1,5),W(1,11),GC_7,AMP(32))
      CALL VVS2_6_3(W(1,1),W(1,4),GC_64,GC_10,MDL_MX0,MDL_WX0,W(1,13))
C     Amplitude(s) for diagram number 31
      CALL VVSS1_3_0(W(1,2),W(1,9),W(1,13),W(1,3),GC_62,GC_13,AMP(33))
C     Amplitude(s) for diagram number 32
      CALL VVVS1_2_0(W(1,16),W(1,2),W(1,9),W(1,3),GC_65,GC_11,AMP(34))
      CALL VVV8P0_1(W(1,16),W(1,2),GC_6,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 33
      CALL VVS2_6_0(W(1,9),W(1,13),W(1,3),GC_64,GC_10,AMP(35))
C     Amplitude(s) for diagram number 34
      CALL VVV8_0(W(1,2),W(1,9),W(1,11),GC_6,AMP(36))
      CALL FFV1_1(W(1,5),W(1,1),GC_7,ZERO,ZERO,W(1,11))
      CALL FFV1_1(W(1,11),W(1,4),GC_7,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 35
      CALL FFV1_0(W(1,6),W(1,13),W(1,18),GC_7,AMP(37))
      CALL FFV1P0_3(W(1,6),W(1,11),GC_7,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 36
      CALL VVV8_0(W(1,18),W(1,4),W(1,13),GC_6,AMP(38))
C     Amplitude(s) for diagram number 37
      CALL FFV1_0(W(1,12),W(1,11),W(1,18),GC_7,AMP(39))
C     Amplitude(s) for diagram number 38
      CALL VVS2_6_0(W(1,7),W(1,13),W(1,3),GC_64,GC_10,AMP(40))
C     Amplitude(s) for diagram number 39
      CALL FFV1_0(W(1,17),W(1,11),W(1,8),GC_7,AMP(41))
      CALL FFV1_1(W(1,11),W(1,2),GC_7,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 40
      CALL FFV1_0(W(1,6),W(1,16),W(1,8),GC_7,AMP(42))
C     Amplitude(s) for diagram number 41
      CALL VVV8_0(W(1,2),W(1,8),W(1,13),GC_6,AMP(43))
      CALL VVVS1_2P0_1(W(1,2),W(1,4),W(1,3),GC_65,GC_11,ZERO,ZERO,W(1
     $ ,13))
C     Amplitude(s) for diagram number 42
      CALL FFV1_0(W(1,6),W(1,11),W(1,13),GC_7,AMP(44))
      CALL FFV1_2(W(1,6),W(1,1),GC_7,ZERO,ZERO,W(1,11))
      CALL FFV1_2(W(1,11),W(1,4),GC_7,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 43
      CALL FFV1_0(W(1,16),W(1,5),W(1,18),GC_7,AMP(45))
      CALL FFV1P0_3(W(1,11),W(1,5),GC_7,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 44
      CALL VVV8_0(W(1,18),W(1,4),W(1,16),GC_6,AMP(46))
C     Amplitude(s) for diagram number 45
      CALL FFV1_0(W(1,11),W(1,10),W(1,18),GC_7,AMP(47))
C     Amplitude(s) for diagram number 46
      CALL VVS2_6_0(W(1,7),W(1,16),W(1,3),GC_64,GC_10,AMP(48))
C     Amplitude(s) for diagram number 47
      CALL FFV1_0(W(1,11),W(1,15),W(1,8),GC_7,AMP(49))
      CALL FFV1_2(W(1,11),W(1,2),GC_7,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 48
      CALL FFV1_0(W(1,14),W(1,5),W(1,8),GC_7,AMP(50))
C     Amplitude(s) for diagram number 49
      CALL VVV8_0(W(1,2),W(1,8),W(1,16),GC_6,AMP(51))
C     Amplitude(s) for diagram number 50
      CALL FFV1_0(W(1,11),W(1,5),W(1,13),GC_7,AMP(52))
      CALL VVV8P0_1(W(1,1),W(1,18),GC_6,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 51
      CALL FFV1_0(W(1,6),W(1,10),W(1,11),GC_7,AMP(53))
      CALL FFV1_1(W(1,10),W(1,1),GC_7,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 52
      CALL FFV1_0(W(1,6),W(1,16),W(1,18),GC_7,AMP(54))
C     Amplitude(s) for diagram number 53
      CALL FFV1_0(W(1,12),W(1,5),W(1,11),GC_7,AMP(55))
      CALL FFV1_2(W(1,12),W(1,1),GC_7,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 54
      CALL FFV1_0(W(1,16),W(1,5),W(1,18),GC_7,AMP(56))
C     Amplitude(s) for diagram number 55
      CALL VVVV1_0(W(1,1),W(1,18),W(1,4),W(1,9),GC_8,AMP(57))
      CALL VVVV3_0(W(1,1),W(1,18),W(1,4),W(1,9),GC_8,AMP(58))
      CALL VVVV4_0(W(1,1),W(1,18),W(1,4),W(1,9),GC_8,AMP(59))
C     Amplitude(s) for diagram number 56
      CALL VVV8_0(W(1,4),W(1,9),W(1,11),GC_6,AMP(60))
      CALL VVV8P0_1(W(1,1),W(1,9),GC_6,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 57
      CALL VVV8_0(W(1,18),W(1,4),W(1,11),GC_6,AMP(61))
      CALL VVS2_6_3(W(1,2),W(1,4),GC_64,GC_10,MDL_MX0,MDL_WX0,W(1,18))
C     Amplitude(s) for diagram number 58
      CALL VVSS1_3_0(W(1,1),W(1,9),W(1,18),W(1,3),GC_62,GC_13,AMP(62))
C     Amplitude(s) for diagram number 59
      CALL VVVS1_2_0(W(1,1),W(1,7),W(1,9),W(1,3),GC_65,GC_11,AMP(63))
      CALL VVV8P0_1(W(1,1),W(1,7),GC_6,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 60
      CALL VVS2_6_0(W(1,9),W(1,18),W(1,3),GC_64,GC_10,AMP(64))
C     Amplitude(s) for diagram number 61
      CALL VVS2_6_0(W(1,7),W(1,11),W(1,3),GC_64,GC_10,AMP(65))
      CALL FFV1_1(W(1,15),W(1,1),GC_7,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 62
      CALL FFV1_0(W(1,6),W(1,7),W(1,8),GC_7,AMP(66))
      CALL VVV8P0_1(W(1,1),W(1,8),GC_6,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 63
      CALL FFV1_0(W(1,6),W(1,15),W(1,7),GC_7,AMP(67))
      CALL FFV1_2(W(1,17),W(1,1),GC_7,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 64
      CALL FFV1_0(W(1,18),W(1,5),W(1,8),GC_7,AMP(68))
C     Amplitude(s) for diagram number 65
      CALL FFV1_0(W(1,17),W(1,5),W(1,7),GC_7,AMP(69))
C     Amplitude(s) for diagram number 66
      CALL VVVV1_0(W(1,1),W(1,2),W(1,8),W(1,9),GC_8,AMP(70))
      CALL VVVV3_0(W(1,1),W(1,2),W(1,8),W(1,9),GC_8,AMP(71))
      CALL VVVV4_0(W(1,1),W(1,2),W(1,8),W(1,9),GC_8,AMP(72))
C     Amplitude(s) for diagram number 67
      CALL VVV8_0(W(1,2),W(1,9),W(1,7),GC_6,AMP(73))
C     Amplitude(s) for diagram number 68
      CALL VVV8_0(W(1,2),W(1,8),W(1,11),GC_6,AMP(74))
      CALL VVVS1_2P0_1(W(1,1),W(1,2),W(1,3),GC_65,GC_11,ZERO,ZERO,W(1
     $ ,11))
C     Amplitude(s) for diagram number 69
      CALL FFV1_0(W(1,6),W(1,10),W(1,11),GC_7,AMP(75))
C     Amplitude(s) for diagram number 70
      CALL FFV1_0(W(1,12),W(1,5),W(1,11),GC_7,AMP(76))
      CALL VVSS1_3_3(W(1,1),W(1,2),W(1,3),GC_62,GC_13,MDL_MX0,MDL_WX0
     $ ,W(1,12))
C     Amplitude(s) for diagram number 71
      CALL VVS2_6_0(W(1,4),W(1,9),W(1,12),GC_64,GC_10,AMP(77))
C     Amplitude(s) for diagram number 72
      CALL VVV8_0(W(1,11),W(1,4),W(1,9),GC_6,AMP(78))
      CALL VVVV1P0_1(W(1,1),W(1,2),W(1,4),GC_8,ZERO,ZERO,W(1,11))
      CALL VVVV3P0_1(W(1,1),W(1,2),W(1,4),GC_8,ZERO,ZERO,W(1,12))
      CALL VVVV4P0_1(W(1,1),W(1,2),W(1,4),GC_8,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 73
      CALL VVS2_6_0(W(1,11),W(1,9),W(1,3),GC_64,GC_10,AMP(79))
      CALL VVS2_6_0(W(1,12),W(1,9),W(1,3),GC_64,GC_10,AMP(80))
      CALL VVS2_6_0(W(1,10),W(1,9),W(1,3),GC_64,GC_10,AMP(81))
      CALL VVVS1_2P0_1(W(1,1),W(1,4),W(1,3),GC_65,GC_11,ZERO,ZERO,W(1
     $ ,10))
C     Amplitude(s) for diagram number 74
      CALL FFV1_0(W(1,6),W(1,15),W(1,10),GC_7,AMP(82))
C     Amplitude(s) for diagram number 75
      CALL FFV1_0(W(1,17),W(1,5),W(1,10),GC_7,AMP(83))
      CALL VVSS1_3_3(W(1,1),W(1,4),W(1,3),GC_62,GC_13,MDL_MX0,MDL_WX0
     $ ,W(1,17))
C     Amplitude(s) for diagram number 76
      CALL VVS2_6_0(W(1,2),W(1,9),W(1,17),GC_64,GC_10,AMP(84))
C     Amplitude(s) for diagram number 77
      CALL VVV8_0(W(1,10),W(1,2),W(1,9),GC_6,AMP(85))
      CALL VVSS1_3_3(W(1,2),W(1,4),W(1,3),GC_62,GC_13,MDL_MX0,MDL_WX0
     $ ,W(1,10))
C     Amplitude(s) for diagram number 78
      CALL VVS2_6_0(W(1,1),W(1,9),W(1,10),GC_64,GC_10,AMP(86))
C     Amplitude(s) for diagram number 79
      CALL VVV8_0(W(1,1),W(1,13),W(1,9),GC_6,AMP(87))
      CALL VVVVS1P0_1(W(1,1),W(1,2),W(1,4),W(1,3),GC_12,ZERO,ZERO,W(1
     $ ,13))
      CALL VVVVS2P0_1(W(1,1),W(1,2),W(1,4),W(1,3),GC_12,ZERO,ZERO,W(1
     $ ,9))
      CALL VVVVS3P0_1(W(1,1),W(1,2),W(1,4),W(1,3),GC_12,ZERO,ZERO,W(1
     $ ,10))
C     Amplitude(s) for diagram number 80
      CALL FFV1_0(W(1,6),W(1,5),W(1,13),GC_7,AMP(88))
      CALL FFV1_0(W(1,6),W(1,5),W(1,9),GC_7,AMP(89))
      CALL FFV1_0(W(1,6),W(1,5),W(1,10),GC_7,AMP(90))
      JAMP(1)=+IMAG1*AMP(1)+AMP(3)+IMAG1*AMP(5)+AMP(7)+AMP(8)+AMP(9)
     $ +IMAG1*AMP(10)+AMP(12)+IMAG1*AMP(21)-AMP(22)+AMP(23)-AMP(25)
     $ +AMP(26)+IMAG1*AMP(38)-AMP(39)+IMAG1*AMP(40)-AMP(42)+IMAG1
     $ *AMP(43)+IMAG1*AMP(44)+IMAG1*AMP(55)+AMP(57)-AMP(59)+AMP(60)
     $ -AMP(61)+AMP(63)+AMP(64)-AMP(65)+AMP(70)-AMP(72)-AMP(74)+IMAG1
     $ *AMP(76)+AMP(78)+AMP(79)-AMP(81)+AMP(87)-AMP(90)+AMP(88)
      JAMP(2)=-IMAG1*AMP(10)-AMP(12)+IMAG1*AMP(16)-AMP(17)+AMP(24)
     $ +AMP(25)+AMP(27)+IMAG1*AMP(28)+AMP(30)+IMAG1*AMP(32)+AMP(34)
     $ +AMP(35)+AMP(36)-AMP(37)-IMAG1*AMP(38)-IMAG1*AMP(40)-AMP(41)
     $ -IMAG1*AMP(43)-IMAG1*AMP(44)+AMP(58)+AMP(59)+AMP(61)-AMP(63)
     $ -AMP(64)+AMP(65)+IMAG1*AMP(69)+AMP(71)+AMP(72)+AMP(73)+AMP(74)
     $ -AMP(80)-AMP(79)+IMAG1*AMP(83)+AMP(85)-AMP(87)-AMP(89)-AMP(88)
      JAMP(3)=+2D0*(-AMP(62)-AMP(86))
      JAMP(4)=-IMAG1*AMP(1)-AMP(3)-IMAG1*AMP(5)-AMP(7)-AMP(8)-AMP(9)
     $ +IMAG1*AMP(13)-AMP(15)-IMAG1*AMP(21)-AMP(23)-AMP(24)-AMP(26)
     $ -AMP(27)+IMAG1*AMP(29)-AMP(30)+IMAG1*AMP(31)-AMP(34)-AMP(35)
     $ -AMP(36)-IMAG1*AMP(55)-AMP(56)-AMP(57)-AMP(58)-AMP(60)-AMP(66)
     $ +IMAG1*AMP(67)-AMP(70)-AMP(71)-AMP(73)-IMAG1*AMP(76)-AMP(78)
     $ +AMP(80)+AMP(81)+IMAG1*AMP(82)-AMP(85)+AMP(90)+AMP(89)
      JAMP(5)=+IMAG1*AMP(11)-AMP(12)-IMAG1*AMP(13)-AMP(14)+AMP(24)
     $ +AMP(25)+AMP(27)-IMAG1*AMP(29)+AMP(30)-IMAG1*AMP(31)+AMP(34)
     $ +AMP(35)+AMP(36)-AMP(45)+IMAG1*AMP(46)+IMAG1*AMP(48)-AMP(49)
     $ +IMAG1*AMP(51)+IMAG1*AMP(52)+AMP(58)+AMP(59)+AMP(61)-AMP(63)
     $ -AMP(64)+AMP(65)-IMAG1*AMP(67)+AMP(71)+AMP(72)+AMP(73)+AMP(74)
     $ -AMP(80)-AMP(79)-IMAG1*AMP(82)+AMP(85)-AMP(87)-AMP(89)-AMP(88)
      JAMP(6)=+2D0*(-AMP(33)-AMP(84))
      JAMP(7)=+IMAG1*AMP(2)-AMP(3)+IMAG1*AMP(4)-AMP(7)-AMP(8)-AMP(9)
     $ -IMAG1*AMP(16)-AMP(18)+IMAG1*AMP(19)-AMP(23)-AMP(24)-AMP(26)
     $ -AMP(27)-IMAG1*AMP(28)-AMP(30)-IMAG1*AMP(32)-AMP(34)-AMP(35)
     $ -AMP(36)+IMAG1*AMP(53)-AMP(54)-AMP(57)-AMP(58)-AMP(60)-AMP(68)
     $ -IMAG1*AMP(69)-AMP(70)-AMP(71)-AMP(73)+IMAG1*AMP(75)-AMP(78)
     $ +AMP(80)+AMP(81)-IMAG1*AMP(83)-AMP(85)+AMP(90)+AMP(89)
      JAMP(8)=-IMAG1*AMP(2)+AMP(3)-IMAG1*AMP(4)+AMP(7)+AMP(8)+AMP(9)
     $ -IMAG1*AMP(11)+AMP(12)-IMAG1*AMP(19)-AMP(20)+AMP(23)-AMP(25)
     $ +AMP(26)-IMAG1*AMP(46)-AMP(47)-IMAG1*AMP(48)-AMP(50)-IMAG1
     $ *AMP(51)-IMAG1*AMP(52)-IMAG1*AMP(53)+AMP(57)-AMP(59)+AMP(60)
     $ -AMP(61)+AMP(63)+AMP(64)-AMP(65)+AMP(70)-AMP(72)-AMP(74)-IMAG1
     $ *AMP(75)+AMP(78)+AMP(79)-AMP(81)+AMP(87)-AMP(90)+AMP(88)
      JAMP(9)=+2D0*(-AMP(6)-AMP(77))

      MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        MATRIX = MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE GET_ME(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE INITIALISE(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*180 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NCOMB
      PARAMETER (NCOMB=32)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/BORN_HEL_CONFIGS/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

